practice-21-5-web/Controllers/AccountController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using practice_21_5_library.Data;
using practice_21_5_library.Models;

namespace practice_21_5_web.Controllers
{
    public class AccountController : Controller
    {
        AccountDataApi accountDataApi;

        public AccountController()
        {
            accountDataApi = new AccountDataApi();
        }

        [HttpGet]
        public IActionResult Login(string returnUrl)
        {
            return View(new UserLogin()
            {
                ReturnUrl = returnUrl
            });
        }

        [HttpPost]
        public async Task<IActionResult> Login(UserLogin userLogin)
        {
            if (!string.IsNullOrEmpty(await accountDataApi.Token(userLogin)))
            {
                return Redirect(userLogin.ReturnUrl);
            }
            else
            {
                ModelState.AddModelError("", "Пользователь не найден");
                return View();
            }
        }


        [HttpGet]
        public IActionResult Register()
        {
            if (AuthUser.IsAuthenticated) return RedirectToAction("Index", "Home");
            return View(new UserRegistration());
        }

        [HttpPost]
        public async Task<ActionResult> Register(UserRegistration userRegistration)
        {
            List<string> resList = await accountDataApi.Register(userRegistration);
            if (resList.First().Equals("null"))
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                foreach (var err in resList)
                {
                    ModelState.AddModelError("", err);
                }
                return View(userRegistration);
            }
        }

        [HttpPost]
        public IActionResult Logout()
        {
            AuthUser.LogoutAuthUser();
            return RedirectToAction("Index", "Home");
        }
    }
}

practice-21-5-web/Controllers/ContactsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using practice_21_5_library.Data;
using practice_21_5_library.Models;
using System.Text.RegularExpressions;

namespace practice_21_5_web.Controllers
{
    public class ContactsController : Controller
    {
        ContactDataApi contactDataApi;

        public ContactsController()
        {
            contactDataApi = new ContactDataApi();
        }

        public async Task<IActionResult> Index(int id, string err = "")
        {
            Contact currentContact = await contactDataApi.GetContacts(id);
            ViewBag.Error = err;
            return View(currentContact);
        }

        public async Task<IActionResult> Delete(int? id) => await ContactPage(id);

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            Contact contact = await contactDataApi.GetContacts(id);
            if (contact != null)
            {
                await contactDataApi.DeleteContact(id);
            }
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Edit(int? id) => await ContactPage(id);

        [HttpPost]
        public async Task<IActionResult> Edit(int id, string lastName, string firstName, string surName, string phoneNumber,
            string address, string description)
        {
            Contact contact = await contactDataApi.GetContacts(id);
            if (contact != null)
            {
                bool isPhoneNumber = Regex.IsMatch(phoneNumber, @"^(\+[0-9]{11})$");
                if (isPhoneNumber)
                {
                    contact.LastName = lastName;
                    contact.FirstName = firstName;
                    contact.SurName = ValueOrDefault(surName);
                    contact.PhoneNumber = phoneNumber;
                    contact.Address = address;
                    contact.Description = ValueOrDefault(description);

                    await contactDataApi.UpdateContact(contact);
                }
                else
                {
                    return RedirectToAction("Index", new { id = id, err = "Неверный номер телефона" });
                }
            }

            return RedirectToAction("Index", new { id = id });
        }

        private async Task<IActionResult> ContactPage(int? id)
        {
            if (id != null)
            {
                Contact? contact = await contactDataApi.GetContacts(id);
                if (contact != null) return RedirectToAction("Index", new { id = id });
            }
            return NotFound();
        }

        private string ValueOrDefault(string value)
        {
            if (!string.IsNullOrEmpty(value)) return value;
            else return "";
        }
    }
}

practice-21-5-web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using practice_21_5_library.Data;
using practice_21_5_library.Models;
using System.Text.RegularExpressions;

namespace practice_21_5_web.Controllers
{
    public class HomeController : Controller
    {
        ContactDataApi contactDataApi;

        public HomeController()
        {
            contactDataApi = new ContactDataApi();
        }

        public async Task<IActionResult> Index(string err = "")
        {
            ViewBag.Contacts = await contactDataApi.GetContacts();
            ViewBag.Error = err;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(string lastName, string firstName, string surName, string phoneNumber,
           string address, string description)
        {

            if (string.IsNullOrEmpty(surName)) surName = "";
            if (string.IsNullOrEmpty(description)) description = "";
            bool isPhoneNumber = Regex.IsMatch(phoneNumber, @"^(\+[0-9]{11})$");
            if(isPhoneNumber)
            {
                Contact contact = new Contact
                {
                    LastName = lastName,
                    FirstName = firstName,
                    SurName = surName,
                    PhoneNumber = phoneNumber,
                    Address = address,
                    Description = description
                };
                await contactDataApi.AddContact(contact);
                return RedirectToAction("Index");
            }
            else
            {
                
                return RedirectToAction("Index", new { err = "Неверный номер телефона" });
            }

        }
    }
}

practice-21-5-web/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using practice_21_5_library.Data;
using practice_21_5_library.Models;

namespace practice_21_5_web.Controllers
{
    public class UserController : Controller
    {
        UserDataApi userDataApi;

        public UserController()
        {
            userDataApi = new UserDataApi();
        }

        public async Task<IActionResult> Index()
        {
            if (AuthUser.Role == "admin")
            {
                ViewBag.Users = await GetUsersList();
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public async Task<ActionResult> Index(UserRegistration userRegistration)
        {
            List<string> resList = await userDataApi.Add(userRegistration);
            if (resList.First().Equals("Ok"))
            {
                return RedirectToAction("Index", "User");
            }
            else
            {
                foreach (var err in resList)
                {
                    ModelState.AddModelError("", err);
                }
                ViewBag.Users = await GetUsersList();
                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            User user = await userDataApi.GetUser(id);
            if (user != null)
            {
                await userDataApi.DeleteUser(id);
            }
            return RedirectToAction("Index", "User");
        }

        private async Task<List<User>> GetUsersList()
        {
            IEnumerable<User> users = await userDataApi.GetUser();
            List<User> result = users.ToList();
            result.RemoveAll(d => d.UserName == AuthUser.UserName);
            return result;
        }
    }
}

practice-21-5-web/ViewComponents/LogoutViewViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace practice_21_5_web.ViewComponents
{
    public class LogoutViewViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

practice-21-5-web/Views/Contacts/Index.cshtml
@model practice_21_5_library.Models.Contact
@{
    ViewData["Title"] = $"Контакт {Model.Id}" ;
    Layout = "_Layout";
}
<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>          
    <h3 class="display-4 ms-3">Контакт @Model.Id</h3>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Фамилиия</th>
                <th scope="col">Имя</th>
                <th scope="col">Отчество</th>
                <th scope="col">Номер телефона</th>
                <th scope="col">Адрес</th>
                <th scope="col">Описание</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">@Model.Id</th>
                <td>@Model.LastName</td>
                <td>@Model.FirstName</td>
                <td>@Model.SurName</td>
                <td>@Model.PhoneNumber</td>
                <td>@Model.Address</td>
                <td>@Model.Description</td>
            </tr>
        </tbody>
  </table>

  <div class="container">
    <div class="row justify-content-between">
        <div class="col-4">
            <a asp-controller="Home" asp-action="Index" class="btn btn-outline-dark">Назад</a>
        </div>
        @if (AuthUser.Role == "admin")
            {
                <div class="col-4">
                    <a class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#editModal">Редактировать</a>
                    <a class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">Удалить</a>
                </div>
            }
    </div>
  </div>
<!-- Modal -->
<div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="editModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editModalLabel">Удалить контакт</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
            <div class="modal-header">
        <h7 class="modal-title text-danger" id="addModalLabel">@ViewBag.Error</h7>
      </div>
      <div class="modal-body">
          <form method="post" asp-controller="Contacts" asp-action="Edit" asp-route-id="@Model.Id" class="needs-validation">
  <div class="mb-3">
    <label for="inputLastName" class="form-label">Фамилия</label>
    <input type="text" class="form-control" id="inputLastName" value="@Model.LastName" name="lastName" required>
  </div>
  <div class="mb-3">
    <label for="inputFirstName" class="form-label">Имя</label>
    <input type="text" class="form-control" id="inputFirstName" value="@Model.FirstName" name="firstName" required>
  </div>
  <div class="mb-3">
    <label for="inputSurName" class="form-label">Отчество</label>
    <input type="text" class="form-control" id="inputSurName" value="@Model.SurName" name="surName">
  </div>
    <div class="mb-3">
    <label for="inputPhoneNumber" class="form-label">Телефон</label>
    <input type="tel" class="form-control" id="inputPhoneNumber" value="@Model.PhoneNumber" name="phoneNumber" required>
  </div>
      <div class="mb-3">
    <label for="inputAddress" class="form-label">Адрес</label>
    <input type="text" class="form-control" id="inputAddress" value="@Model.Address" name="address" required>
  </div>
        <div class="mb-3">
    <label for="inputDescription" class="form-label">Описание</label>
    <input type="text" class="form-control" id="inputDescription" value="@Model.Description" name="description">
  </div>
  <button type="submit" class="btn btn-primary">Редактировать</button>
</form>
      </div>
    </div>
  </div>
</div>
<!-- Modal -->


<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Удалить контакт</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Вы действительно хотите удалить этот контакт?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Нет</button>
        <form method="post" asp-controller="Contacts" asp-action="Delete" asp-route-id="@Model.Id">
            <input type="submit" value="Удалить" class="btn btn-danger"/>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- Modal -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

practice-21-5-web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Список контактов";
    Layout = "_Layout";
}
<!DOCTYPE html>
 
<html>

<body>
    <h1 class="display-3 ms-3">Контакты</h1>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Фамилия</th>
      <th scope="col">Имя</th>
      <th scope="col">Отчество</th>
    </tr>
  </thead>
  <tbody>
        @foreach (Contact contact in ViewBag.Contacts)
            {
            <tr>
                <th scope="row"><a asp-controller="Contacts" asp-action="Index" asp-route-id="@contact.Id" class="link-dark">@contact.Id</a></th>
                <td>@contact.LastName</td>
                <td>@contact.FirstName</td>
                <td>@contact.SurName</td>
            </tr>
        }

  </tbody>
</table>

@if (AuthUser.IsAuthenticated)
    {
        <a class="btn btn-primary ms-3" data-bs-toggle="modal" data-bs-target="#addModal">Добавить</a>
    }
  

<!-- Modal -->
<div class="modal fade" id="addModal" tabindex="-1" aria-labelledby="addModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addModalLabel">Добавить контакт</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-header">
        <h7 class="modal-title text-danger" id="addModalLabel">@ViewBag.Error</h7>
      </div>

      <div class="modal-body">
          <form method="post" asp-controller="Home" asp-action="Add" class="needs-validation">
  <div class="mb-3">
    <label for="inputLastName" class="form-label">Фамилия</label>
    <input type="text" class="form-control" id="inputLastName" name="lastName" required>
  </div>
  <div class="mb-3">
    <label for="inputFirstName" class="form-label">Имя</label>
    <input type="text" class="form-control" id="inputFirstName" name="firstName" required>
  </div>
  <div class="mb-3">
    <label for="inputSurName" class="form-label">Отчество</label>
    <input type="text" class="form-control" id="inputSurName" name="surName">
  </div>
    <div class="mb-3">
    <label for="inputPhoneNumber" class="form-label">Телефон</label>
    <input type="tel" class="form-control" id="inputPhoneNumber" name="phoneNumber" required>
  </div>
      <div class="mb-3">
    <label for="inputAddress" class="form-label">Адрес</label>
    <input type="text" class="form-control" id="inputAddress" name="address" required>
  </div>
        <div class="mb-3">
    <label for="inputDescription" class="form-label">Описание</label>
    <input type="text" class="form-control" id="inputDescription" name="description">
  </div>
  <button type="submit" class="btn btn-primary">Добавить</button>
</form>
      </div>
    </div>
  </div>
</div>
<!-- Modal -->

</body>
</html>

practice-21-5-web/Views/Shared/Components/LogoutView/Default.cshtml
@if (AuthUser.IsAuthenticated)
{  <div class="container">
    <div class="row justify-content-between">
    <div class="col-4">
        <a asp-controller="Home" asp-action="Index" class="navbar-brand">@AuthUser.UserName</a>
    </div>
    <div class="col-4">
        <a asp-controller="User" asp-action="Index" class="navbar-brand">Пользователи</a>
    </div>
    <div class="col-2">
                <form asp-controller="Account" asp-action="Logout" id="logoutForm" asp-antiforgery="true">
            <a class="navbar-brand" href="#" onclick="document.getElementById('logoutForm').submit()">Выйти</a>
        </form>
    </div>
            
    </div>
    </div>

}
else
{
    <div class="btn-groug pull-right">
        <a asp-controller="Account" asp-action="Login" asp-route-returnUrl="@Context.Request.Path@Context.Request.QueryString" class="navbar-brand">Войти</a>
        <a asp-controller="Account" asp-action="Register" class="navbar-brand">Регистрация</a>
    </div>
        
}

practice-21-5-web/Views/Shared/_Layout.cshtml
﻿<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>@ViewData["Title"]</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    </head>
    <body class="container">
                <nav class="navbar navbar-light bg-light">
            <div>
                @await Component.InvokeAsync("LogoutView")
            </div>
        </nav>
        <div class="container">
            @RenderBody()
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </body>
</html>

practice-21-5-web/Views/User/Index.cshtml
@model practice_21_5_library.Models.UserRegistration
@{
    ViewData["Title"] = "Список пользователей";
    Layout = "_Layout";
}
<!DOCTYPE html>
 
<html>
<body>
    @if (AuthUser.Role == "admin")
    {
    <h1 class="display-3 ms-3">Пользователи</h1>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Логин</th>
    </tr>
  </thead>
  <tbody>
        @foreach (User user in ViewBag.Users)
            {
            <tr>
                <td>@user.Id</td>
                <td>@user.UserName</td>
                <td>
                    <form method="post" asp-controller="User" asp-action="Delete" asp-route-id="@user.Id">
                        <input type="submit" value="Удалить" class="btn btn-danger"/>
                    </form>
                </td>
            </tr>
        }

  </tbody>
</table>


            <!-- Modal -->
<div class="modal fade" id="deleteModel" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Удалить пользователя</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Вы действительно хотите удалить этого пользователя?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Нет</button>
        <form method="post" asp-controller="User" asp-action="Delete" asp-route-id="">
            <input type="submit" value="Удалить" class="btn btn-danger"/>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- Modal -->     
           <form method="post" asp-controller="User" asp-action="Index" asp-antiforgery="true" class="needs-validation">
  <div asp-validation-summary="ModelOnly" class="text-danger"></div>
  <div class="mb-3">
    <label for="inputLogin" class="form-label">Логин</label>
    <input type="text" class="form-control" id="inputLogin" asp-for="LoginProp" required>
  </div>
  <div class="mb-3">
    <label for="inputPassword" class="form-label">Пароль</label>
    <input class="form-control" id="inputPassword" asp-for="Password" required>
  </div>
    <div class="mb-3">
    <label for="inputComfirmPassword" class="form-label">Повторите пароль</label>
    <input class="form-control" id="inputComfirmPassword" asp-for="ConfirmPassword" required>
  </div>
  <button type="submit" class="btn btn-primary">Добавить</button>
</form>
    }
</body>
</html>